# Site settings
title: Jasen Kundalic
name: Jasen Kundalic

# Build settings
markdown: kramdown

#Any buzzword skills you want to include
skills:
 - C#
 - SQL
 - ASP.NET

#Work experience is required
roles:
 - title: Istraživač
   start: 2013
   end: 2016
   employer: Medicinski fakultet Niš
   
 - title: Istraživač saradnik na projektima
   start: 2017
   end: 2018
   employer: Univerzitet u Nišu

#Education is required
education:
 - level: Doktor stomatologije
   date: 2011
   school: Medicinski fakultet Niš
